model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"
service_tier = "fast"

[sandbox_workspace_write]
network_access = true 

[projects."/home/nia"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot/dotfiles"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot/wbs-input-support"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot/nixtest"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot/nuxt-learning-app"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[tui]
status_line = ["model-with-reasoning", "context-remaining", "current-dir"]

[plugins."github@openai-curated"]
enabled = true
